#!/usr/bin/env bash

echo "pre-commit hook"
node ./node_modules/.bin/eslint -c ./.eslintrc.json ./src/modules/ || exit 1

if [ $? -ne 0 ]
  then echo "Bad code! :(" && exit 1
fi

if grep -r --ignore-case "TODO!" ./src
  then echo "Can't commit with TODO!" && exit 1
fi

if grep -r --ignore-case "debugger" ./src
  then echo "Can't commit with debugger" && exit 1
fi

if grep -r --ignore-case "<w-i18n" ./src
  then echo "w-i18n should be used only as an attribute, not as a tag name" && exit 1
fi

echo "pre-commit hook >> DONE"

exit 0
